// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwpjlenmopdsaswqdlop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3cGpsZW5tb3Bkc2Fzd3FkbG9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1NjA4ODUsImV4cCI6MjA5MjEzNjg4NX0.EdAErVPs6flDJZ3SSbmO5oQJrvwaINBlUJ5PMUZb-Rg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});